language: cpp
script: scons alltests ${BUILD_ARGS}

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libsqlite3-dev
            - libboost-iostreams-dev
            - libboost-test-dev
      env:
         - BUILD_ARGS="CC=gcc-5 CXX=g++-5"
